name: Tests runner on pull request

on:
  pull_request:
    types: [ opened, edited ]
    branches:
      -main
      -testing-actions

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'coretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

      - name: Tests
        run: ./gradlew test --tests "*"