name: Tests runner on pull request

on:
#  pull_request:
#    types: [ opened, edited ]
#    branches:
#      -main
  push

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Tests
        run: ./gradlew test --tests "*"